services:
  sensor_app:
    image: glopix/onewire-to-mqtt
    restart: unless-stopped
    volumes:
      - ./config.ini:/app/config.ini
      - /sys/bus/w1/devices:/sys/bus/w1/devices:ro  # Read-only mount for sensor data
    environment:
      - PYTHONUNBUFFERED=1
#    devices:
#      - "/dev/mem:/dev/mem"  # May be needed for some sensor setups
    privileged: true  # Required for accessing hardware sensors

